-- FAMILJA - Supabase Free setup
-- Ekzekuto të gjithë këtë skedar një herë te Supabase -> SQL Editor.

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.media enable row level security;

-- Projekti u krijua me "Automatically expose new tables" OFF,
-- prandaj japim vetëm privilegjet që i duhen rolit authenticated.
grant select, insert, update, delete on table public.media to authenticated;

-- Për kolonën identity.
do $$
declare
  seq_name text;
begin
  select pg_get_serial_sequence('public.media', 'id') into seq_name;
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end $$;

drop policy if exists "Familja can read media" on public.media;
create policy "Familja can read media"
on public.media
for select
to authenticated
using (true);

drop policy if exists "Admin can insert media" on public.media;
drop policy if exists "Family can insert media" on public.media;
create policy "Family can insert media"
on public.media
for insert
to authenticated
with check (
  auth.email() = 'admin@familja.local'
  or (
    auth.email() = 'familja@familja.local'
    and type like 'image/%'
    and storage_path like 'family/%'
  )
);

drop policy if exists "Admin can update media" on public.media;
create policy "Admin can update media"
on public.media
for update
to authenticated
using (auth.email() = 'admin@familja.local')
with check (auth.email() = 'admin@familja.local');

drop policy if exists "Admin can delete media" on public.media;
drop policy if exists "Family can delete own-path media" on public.media;
create policy "Family can delete own-path media"
on public.media
for delete
to authenticated
using (
  auth.email() = 'admin@familja.local'
  or (
    auth.email() = 'familja@familja.local'
    and storage_path like 'family/%'
  )
);

insert into storage.buckets (id, name, public, file_size_limit)
values ('familja-media', 'familja-media', false, 52428800)
on conflict (id) do update
set public = false,
    file_size_limit = 52428800;

drop policy if exists "Familja can view storage" on storage.objects;
create policy "Familja can view storage"
on storage.objects
for select
to authenticated
using (bucket_id = 'familja-media');

drop policy if exists "Admin can upload storage" on storage.objects;
drop policy if exists "Family can upload storage" on storage.objects;
create policy "Family can upload storage"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'familja-media'
  and (
    auth.email() = 'admin@familja.local'
    or (
      auth.email() = 'familja@familja.local'
      and name like 'family/%'
    )
  )
);

drop policy if exists "Admin can update storage" on storage.objects;
create policy "Admin can update storage"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'familja-media'
  and auth.email() = 'admin@familja.local'
)
with check (
  bucket_id = 'familja-media'
  and auth.email() = 'admin@familja.local'
);

drop policy if exists "Admin can delete storage" on storage.objects;
drop policy if exists "Family can delete own-path storage" on storage.objects;
create policy "Family can delete own-path storage"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'familja-media'
  and (
    auth.email() = 'admin@familja.local'
    or (
      auth.email() = 'familja@familja.local'
      and name like 'family/%'
    )
  )
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'media'
  ) then
    alter publication supabase_realtime add table public.media;
  end if;
end $$;


-- Shared Information board
create table if not exists public.information (
  id bigint generated by default as identity primary key,
  author text not null check (char_length(author) between 1 and 40),
  message text not null check (char_length(message) between 1 and 1000),
  user_id uuid not null default auth.uid(),
  created_at timestamptz not null default now()
);

alter table public.information enable row level security;

grant select, insert, delete on table public.information to authenticated;

do $$
declare
  seq_name text;
begin
  select pg_get_serial_sequence('public.information', 'id') into seq_name;
  if seq_name is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq_name);
  end if;
end $$;

drop policy if exists "Family can read information" on public.information;
create policy "Family can read information"
on public.information
for select
to authenticated
using (true);

drop policy if exists "Family can write information" on public.information;
create policy "Family can write information"
on public.information
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "Admin can delete information" on public.information;
create policy "Admin can delete information"
on public.information
for delete
to authenticated
using (auth.email() = 'admin@familja.local');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'information'
  ) then
    alter publication supabase_realtime add table public.information;
  end if;
end $$;


-- Admin-only storage usage meter (bytes used in familja-media).
create or replace function public.admin_storage_usage()
returns bigint
language sql
security definer
set search_path = public, storage
as $$
  select
    case
      when auth.email() = 'admin@familja.local' then
        coalesce(
          sum(
            case
              when (metadata->>'size') ~ '^[0-9]+$'
              then (metadata->>'size')::bigint
              else 0
            end
          ),
          0
        )::bigint
      else 0::bigint
    end
  from storage.objects
  where bucket_id = 'familja-media';
$$;

revoke all on function public.admin_storage_usage() from public;
grant execute on function public.admin_storage_usage() to authenticated;
