-- FAMILJA - Supabase Free setup
-- Ekzekuto të gjithë këtë skedar një herë te Supabase -> SQL Editor.

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);

alter table public.media enable row level security;

drop policy if exists "Familja can read media" on public.media;
create policy "Familja can read media"
on public.media
for select
to authenticated
using (true);

drop policy if exists "Admin can insert media" on public.media;
create policy "Admin can insert media"
on public.media
for insert
to authenticated
with check ((auth.jwt() ->> 'email') = 'admin@familja.local');

drop policy if exists "Admin can update media" on public.media;
create policy "Admin can update media"
on public.media
for update
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@familja.local')
with check ((auth.jwt() ->> 'email') = 'admin@familja.local');

drop policy if exists "Admin can delete media" on public.media;
create policy "Admin can delete media"
on public.media
for delete
to authenticated
using ((auth.jwt() ->> 'email') = 'admin@familja.local');

insert into storage.buckets (id, name, public, file_size_limit)
values ('familja-media', 'familja-media', false, 52428800)
on conflict (id) do update
set public = false,
    file_size_limit = 52428800;

drop policy if exists "Familja can view storage" on storage.objects;
create policy "Familja can view storage"
on storage.objects
for select
to authenticated
using (bucket_id = 'familja-media');

drop policy if exists "Admin can upload storage" on storage.objects;
create policy "Admin can upload storage"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'familja-media'
  and (auth.jwt() ->> 'email') = 'admin@familja.local'
);

drop policy if exists "Admin can update storage" on storage.objects;
create policy "Admin can update storage"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'familja-media'
  and (auth.jwt() ->> 'email') = 'admin@familja.local'
)
with check (
  bucket_id = 'familja-media'
  and (auth.jwt() ->> 'email') = 'admin@familja.local'
);

drop policy if exists "Admin can delete storage" on storage.objects;
create policy "Admin can delete storage"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'familja-media'
  and (auth.jwt() ->> 'email') = 'admin@familja.local'
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'media'
  ) then
    alter publication supabase_realtime add table public.media;
  end if;
end $$;
