const LANG_KEY="pajaziti-language";
const T={
sq:{title:"Mbretëria e Fundit",turn:"Raundi",you:"Ti",enemy:"Kundërshtari",territory:"Territor",shield:"Mburojë",choose:"Zgjidh një fuqi, pastaj prek një katror të vlefshëm.",back:"Kthehu te lojërat",restart:"Luaj përsëri",win:"🏆 Ti fitove mbretërinë!",lose:"💥 Kundërshtari fitoi.",draw:"🤝 Barazim.",invalid:"Ky veprim nuk mund të përdoret këtu.",computer:"Kompjuteri po luan…",help:"Qëllimi: zgjero territorin dhe pushto kështjellën kundërshtare. Pas 24 raundeve fiton ai me më shumë territor.",cards:"Fuqitë e tua",land:"Tokë",wall:"Mur",soldier:"Ushtar",bridge:"Urë",fire:"Zjarr",water:"Ujë",bomb:"Bombë",guard:"Mburojë",quake:"Tërmet",black:"Diamanti i Zi",rewind:"Koha mbrapsht"},
de:{title:"Das letzte Königreich",turn:"Runde",you:"Du",enemy:"Gegner",territory:"Gebiet",shield:"Schild",choose:"Wähle eine Kraft und tippe dann auf ein gültiges Feld.",back:"Zurück zu den Spielen",restart:"Noch einmal",win:"🏆 Du hast das Königreich gewonnen!",lose:"💥 Der Gegner hat gewonnen.",draw:"🤝 Unentschieden.",invalid:"Diese Aktion ist hier nicht möglich.",computer:"Computer spielt…",help:"Ziel: Erweitere dein Gebiet und erobere die gegnerische Burg. Nach 24 Runden gewinnt das größere Gebiet.",cards:"Deine Kräfte",land:"Land",wall:"Mauer",soldier:"Soldat",bridge:"Brücke",fire:"Feuer",water:"Wasser",bomb:"Bombe",guard:"Schild",quake:"Erdbeben",black:"Schwarzer Diamant",rewind:"Zeit zurück"},
tr:{title:"Son Krallık",turn:"Tur",you:"Sen",enemy:"Rakip",territory:"Bölge",shield:"Kalkan",choose:"Bir güç seç, sonra geçerli bir kareye dokun.",back:"Oyunlara dön",restart:"Tekrar oyna",win:"🏆 Krallığı kazandın!",lose:"💥 Rakip kazandı.",draw:"🤝 Berabere.",invalid:"Bu hamle burada kullanılamaz.",computer:"Bilgisayar oynuyor…",help:"Amaç: bölgeni büyüt ve rakibin kalesini ele geçir. 24 tur sonunda daha büyük bölge kazanır.",cards:"Güçlerin",land:"Toprak",wall:"Duvar",soldier:"Asker",bridge:"Köprü",fire:"Ateş",water:"Su",bomb:"Bomba",guard:"Kalkan",quake:"Deprem",black:"Kara Elmas",rewind:"Zamanı geri al"},
en:{title:"The Last Kingdom",turn:"Round",you:"You",enemy:"Opponent",territory:"Territory",shield:"Shield",choose:"Choose a power, then tap a valid tile.",back:"Back to games",restart:"Play again",win:"🏆 You won the kingdom!",lose:"💥 The opponent won.",draw:"🤝 Draw.",invalid:"That action cannot be used there.",computer:"Computer is playing…",help:"Goal: expand your territory and capture the enemy castle. After 24 rounds, the larger territory wins.",cards:"Your powers",land:"Land",wall:"Wall",soldier:"Soldier",bridge:"Bridge",fire:"Fire",water:"Water",bomb:"Bomb",guard:"Shield",quake:"Earthquake",black:"Black Diamond",rewind:"Time rewind"}
};
const A=[["land","🌱",24,1],["wall","🧱",12,1],["soldier","🛡️",18,1],["bridge","🌉",10,1],["fire","🔥",8,1],["water","🌊",8,1],["bomb","💣",7,1],["guard","🛡️",8,0],["quake","🌍",3,0],["black","💎",3,1],["rewind","⏪",2,0]];
const N=9,P=1,E=2,CP=72,CE=8,MAX=24;let S,H,back,L="sq",pick=null,lock=false;
const x=k=>(T[L]||T.sq)[k]||T.sq[k]||k, K=i=>String(i), rc=i=>[Math.floor(i/N),i%N], id=(r,c)=>r*N+c, inside=(r,c)=>r>=0&&r<N&&c>=0&&c<N;
function near(i){const [r,c]=rc(i),o=[];[[1,0],[-1,0],[0,1],[0,-1]].forEach(([a,b])=>{if(inside(r+a,c+b))o.push(id(r+a,c+b))});return o}
const adj=(i,w)=>near(i).some(n=>S.c[n]===w);
function within(i,w,d=2){const [r,c]=rc(i);for(let rr=0;rr<N;rr++)for(let cc=0;cc<N;cc++)if(S.c[id(rr,cc)]===w&&Math.abs(rr-r)+Math.abs(cc-c)<=d)return true;return false}
function draw(){let n=Math.random()*A.reduce((s,a)=>s+a[2],0);for(const a of A){n-=a[2];if(n<=0)return a}return A[0]}
const hand=()=>[draw(),draw()], count=w=>S.c.filter(v=>v===w).length;
function snap(){return{c:[...S.c],w:[...S.w],ps:S.ps,es:S.es,t:S.t}}
function restore(q){S.c=[...q.c];S.w=new Set(q.w);S.ps=q.ps;S.es=q.es;S.t=q.t}
function reset(){const c=Array(81).fill(0);[72,63,73,64].forEach(i=>c[i]=P);[8,7,17,16].forEach(i=>c[i]=E);S={c,w:new Set(),ps:0,es:0,t:1,h:hand(),msg:x("choose"),over:0,win:0,last:null};pick=null;lock=false;render()}
function css(){if(document.getElementById("kgcss"))return;const s=document.createElement("style");s.id="kgcss";s.textContent=`
.kg{min-height:100%;padding:12px;background:radial-gradient(circle at 50% 5%,#312e81,#111827 50%,#030712);color:#fff}.kgh{display:flex;justify-content:space-between;align-items:center;max-width:720px;margin:auto}.kgh button,.kgr{border:0;border-radius:14px;padding:10px 12px;font-weight:900}.kgh button{background:#fff;color:#111827}.kgt{font-weight:1000;font-size:1.2rem}.kgs{max-width:720px;margin:10px auto;display:grid;grid-template-columns:1fr auto 1fr;gap:8px}.kgs>div{background:#ffffff18;padding:9px;border-radius:15px}.kgs>div:last-child{text-align:right}.kgb{width:min(94vw,560px);aspect-ratio:1;margin:auto;display:grid;grid-template-columns:repeat(9,1fr);gap:3px;padding:5px;background:#020617;border-radius:20px}.kgc{position:relative;border:0;border-radius:7px;background:#334155}.kgc.p{background:linear-gradient(145deg,#60a5fa,#1d4ed8)}.kgc.e{background:linear-gradient(145deg,#fb7185,#be123c)}.kgc.v{outline:3px solid #facc15;outline-offset:-3px}.kgc.castle:after{content:"🏰";position:absolute;inset:0;display:grid;place-items:center;font-size:clamp(16px,5vw,30px)}.kgc.wall:before{content:"🧱";position:absolute;right:0;bottom:0;font-size:clamp(9px,3vw,16px)}.kgcards{max-width:720px;margin:12px auto}.kgcards strong{display:block;text-align:center;margin-bottom:7px}.kgrow{display:grid;grid-template-columns:1fr 1fr;gap:9px}.kgp{border:2px solid transparent;border-radius:17px;padding:12px 8px;background:#fff;color:#111827;font-weight:1000}.kgp.on{border-color:#facc15;background:#fef3c7}.kgm,.kghlp,.kgres{max-width:720px;margin:10px auto;text-align:center}.kgm{min-height:42px;padding:9px;border-radius:14px;background:#ffffff15;font-weight:800}.kghlp{font-size:.88rem;color:#dbeafe}.kgres{padding:14px;border-radius:18px;background:#fff;color:#111827;font-weight:1000}`;document.head.appendChild(s)}
function targets(a,w){const e=w===P?E:P,o=[];for(let i=0;i<81;i++){const v=S.c[i];if(a[0]==="land"&&v===0&&adj(i,w))o.push(i);else if(a[0]==="wall"&&v===w&&!S.w.has(K(i))&&i!==(w===P?CP:CE))o.push(i);else if(a[0]==="soldier"&&v!==w&&adj(i,w))o.push(i);else if(a[0]==="bridge"&&v!==w&&within(i,w))o.push(i);else if(["fire","water","bomb"].includes(a[0])&&v===e)o.push(i);else if(a[0]==="black"&&v===e&&i!==(w===P?CE:CP))o.push(i)}return o}
function instant(a,w){if(a[0]==="guard"){w===P?S.ps++:S.es++;return 1}if(a[0]==="quake"){let q=S.c.map((v,i)=>({v,i})).filter(z=>z.i!==CP&&z.i!==CE&&z.v);for(let n=0;n<Math.min(4,q.length);n++){const k=Math.floor(Math.random()*q.length),i=q.splice(k,1)[0].i;S.c[i]=0;S.w.delete(K(i))}return 1}if(a[0]==="rewind"){if(w===P&&S.last)restore(S.last);return 1}return 0}
function castle(i,w){if(i!==CP&&i!==CE)return 0;const d=i===CE?E:P;if(w===d)return 0;if(d===E&&S.es){S.es--;return 1}if(d===P&&S.ps){S.ps--;return 1}S.c[i]=w;S.over=1;S.win=w;return 1}
function apply(a,i,w){if(a[0]==="land"){S.c[i]=w;return}if(a[0]==="wall"){S.w.add(K(i));return}if(a[0]==="soldier"||a[0]==="bridge"){if(!castle(i,w)){S.c[i]=w;S.w.delete(K(i))}return}if(a[0]==="black"){S.c[i]=w;S.w.delete(K(i));return}if(a[0]==="bomb"){if(S.w.has(K(i)))S.w.delete(K(i));else if(!castle(i,w))S.c[i]=0;return}if(a[0]==="fire"){if(!castle(i,w)){S.c[i]=0;S.w.delete(K(i))}return}if(a[0]==="water"&&i!==CP&&i!==CE){S.c[i]=0;S.w.delete(K(i))}}
function done(){if(S.over)return 1;if(S.t>MAX){const p=count(P)+S.ps*2,e=count(E)+S.es*2;S.over=1;S.win=p>e?P:e>p?E:0;return 1}return 0}
function label(a){return a[1]+" "+x(a[0])}
function render(){const valid=new Set(pick&&pick[3]&&!S.over&&!lock?targets(pick,P):[]);H.innerHTML=`<section class="kg"><div class="kgh"><button id="kgbk">← ${x("back")}</button><div class="kgt">🏰 ${x("title")}</div><button id="kgrs">↻</button></div><div class="kgs"><div><b>🔵 ${x("you")}</b><br>${x("territory")}: ${count(P)} · ${x("shield")}: ${S.ps}</div><div><b>${x("turn")}</b><br>${Math.min(S.t,MAX)}/${MAX}</div><div><b>${x("enemy")} 🔴</b><br>${x("territory")}: ${count(E)} · ${x("shield")}: ${S.es}</div></div><div class="kgb">${S.c.map((v,i)=>`<button class="kgc ${v===P?"p":v===E?"e":""} ${valid.has(i)?"v":""} ${i===CP||i===CE?"castle":""} ${S.w.has(K(i))?"wall":""}" data-cell="${i}"></button>`).join("")}</div>${S.over?`<div class="kgres">${S.win===P?x("win"):S.win===E?x("lose"):x("draw")}<br><button id="kgagain" class="kgr">${x("restart")}</button></div>`:`<div class="kgcards"><strong>${x("cards")}</strong><div class="kgrow">${S.h.map((a,n)=>`<button class="kgp ${pick===a?"on":""}" data-card="${n}">${label(a)}</button>`).join("")}</div></div>`}<div class="kgm">${S.msg}</div><div class="kghlp">${x("help")}</div></section>`;H.querySelector("#kgbk").onclick=()=>back&&back();H.querySelector("#kgrs").onclick=reset;H.querySelector("#kgagain")?.addEventListener("click",reset);H.querySelectorAll("[data-card]").forEach(b=>b.onclick=()=>choose(+b.dataset.card));H.querySelectorAll("[data-cell]").forEach(b=>b.onclick=()=>play(+b.dataset.cell))}
function choose(n){if(S.over||lock)return;const a=S.h[n];pick=a;if(instant(a,P)){S.msg=label(a)+" ✓";pick=null;render();after();return}if(!targets(a,P).length){S.msg=x("invalid");pick=null;S.h=hand();render();return}S.msg=x("choose")+" "+label(a);render()}
function play(i){if(S.over||lock||!pick)return;if(!targets(pick,P).includes(i)){S.msg=x("invalid");render();return}apply(pick,i,P);S.msg=label(pick)+" ✓";pick=null;render();if(!done())after()}
function ai(){S.last=snap();let a;for(let z=0;z<12;z++){a=draw();if(!a[3]||targets(a,E).length)break}if(instant(a,E)){S.msg=x("computer")+" "+label(a);return}const q=targets(a,E);if(!q.length)return;let i=q[Math.floor(Math.random()*q.length)],hit=q.filter(j=>S.c[j]===P);if(hit.includes(CP))i=CP;else if(hit.length&&Math.random()<.72)i=hit[Math.floor(Math.random()*hit.length)];apply(a,i,E);S.msg=x("computer")+" "+label(a)}
function after(){if(S.over)return render();lock=true;S.msg=x("computer");render();setTimeout(()=>{ai();S.t++;S.h=hand();lock=false;done();render()},520)}
export function startKingdomGame(o={}){css();H=o.root||document.getElementById("gamesRoot");back=typeof o.onBack==="function"?o.onBack:null;L=localStorage.getItem(LANG_KEY)||"sq";if(!T[L])L="en";reset()}
