const SHARE_APP_LANG_KEY="pajaziti-language";
const SHARE_BASE_URL="https://htuzevfjmctmjnqrdrrq.supabase.co/functions/v1";
const SHARE_APP_URL=SHARE_BASE_URL+"/diamond-android";
const SHARE_FIRE_URL=SHARE_BASE_URL+"/diamond-firestick";
const SHARE_IOS_URL=SHARE_BASE_URL+"/diamond-iphone";
const SHARE_SMART_URL=SHARE_BASE_URL+"/diamond-download";

const SA={
sq:{tab:"Ndaje appin",title:"Ndaje DIAMOND",desc:"Link permanent për Android. Gjithmonë hap versionin më të ri.",share:"Ndaje",copy:"Kopjo linkun",open:"Hape",copied:"Linku u kopjua.",hint:"Ky link nuk ndryshon pas update-ve.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Link permanent për Downloader / Fire TV Stick. Gjithmonë merr versionin më të ri.",ios:"🍎 iPhone / Safari",iosDesc:"Link permanent për iPhone. Hape në Safari dhe përdor Share → Add to Home Screen.",smart:"🔗 Link universal",smartDesc:"Një link i vetëm që e dallon pajisjen: Android, Fire TV ose iPhone.",iosCopied:"Linku për iPhone u kopjua.",fireCopied:"Linku për Fire TV u kopjua.",smartCopied:"Linku universal u kopjua."},
de:{tab:"App teilen",title:"DIAMOND teilen",desc:"Permanenter Android-Link. Öffnet immer die neueste Version.",share:"Teilen",copy:"Link kopieren",open:"Öffnen",copied:"Link kopiert.",hint:"Dieser Link ändert sich bei Updates nicht.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Permanenter Link für Downloader / Fire TV. Lädt immer die neueste Version.",ios:"🍎 iPhone / Safari",iosDesc:"Permanenter iPhone-Link. In Safari öffnen und Teilen → Zum Home-Bildschirm.",smart:"🔗 Universal-Link",smartDesc:"Ein Link erkennt Android, Fire TV oder iPhone automatisch.",iosCopied:"iPhone-Link kopiert.",fireCopied:"Fire-TV-Link kopiert.",smartCopied:"Universal-Link kopiert."},
tr:{tab:"Uygulamayı paylaş",title:"DIAMOND'u paylaş",desc:"Kalıcı Android bağlantısı. Her zaman en yeni sürümü açar.",share:"Paylaş",copy:"Bağlantıyı kopyala",open:"Aç",copied:"Bağlantı kopyalandı.",hint:"Bu bağlantı güncellemelerde değişmez.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Downloader / Fire TV için kalıcı bağlantı. Her zaman en yeni sürümü alır.",ios:"🍎 iPhone / Safari",iosDesc:"Kalıcı iPhone bağlantısı. Safari'de açıp Paylaş → Ana Ekrana Ekle.",smart:"🔗 Evrensel bağlantı",smartDesc:"Tek bağlantı Android, Fire TV veya iPhone'u otomatik algılar.",iosCopied:"iPhone bağlantısı kopyalandı.",fireCopied:"Fire TV bağlantısı kopyalandı.",smartCopied:"Evrensel bağlantı kopyalandı."},
en:{tab:"Share app",title:"Share DIAMOND",desc:"Permanent Android link. It always opens the newest version.",share:"Share",copy:"Copy link",open:"Open",copied:"Link copied.",hint:"This link does not change after updates.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Permanent Downloader / Fire TV link. It always gets the newest version.",ios:"🍎 iPhone / Safari",iosDesc:"Permanent iPhone link. Open in Safari, then Share → Add to Home Screen.",smart:"🔗 Universal link",smartDesc:"One link automatically detects Android, Fire TV or iPhone.",iosCopied:"iPhone link copied.",fireCopied:"Fire TV link copied.",smartCopied:"Universal link copied."},
it:{tab:"Condividi app",title:"Condividi DIAMOND",desc:"Link Android permanente. Apre sempre la versione più recente.",share:"Condividi",copy:"Copia link",open:"Apri",copied:"Link copiato.",hint:"Questo link non cambia con gli aggiornamenti.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Link permanente per Downloader / Fire TV. Scarica sempre l'ultima versione.",ios:"🍎 iPhone / Safari",iosDesc:"Link iPhone permanente. Apri in Safari e usa Condividi → Aggiungi a Home.",smart:"🔗 Link universale",smartDesc:"Un solo link rileva automaticamente Android, Fire TV o iPhone.",iosCopied:"Link iPhone copiato.",fireCopied:"Link Fire TV copiato.",smartCopied:"Link universale copiato."},
hr:{tab:"Podijeli app",title:"Podijeli DIAMOND",desc:"Stalna Android poveznica. Uvijek otvara najnoviju verziju.",share:"Podijeli",copy:"Kopiraj poveznicu",open:"Otvori",copied:"Poveznica kopirana.",hint:"Ova se poveznica ne mijenja nakon ažuriranja.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Stalna poveznica za Downloader / Fire TV. Uvijek preuzima najnoviju verziju.",ios:"🍎 iPhone / Safari",iosDesc:"Stalna iPhone poveznica. Otvori u Safariju pa Dijeli → Add to Home Screen.",smart:"🔗 Univerzalna poveznica",smartDesc:"Jedna poveznica automatski prepoznaje Android, Fire TV ili iPhone.",iosCopied:"iPhone poveznica kopirana.",fireCopied:"Fire TV poveznica kopirana.",smartCopied:"Univerzalna poveznica kopirana."},
fr:{tab:"Partager l'app",title:"Partager DIAMOND",desc:"Lien Android permanent. Il ouvre toujours la dernière version.",share:"Partager",copy:"Copier le lien",open:"Ouvrir",copied:"Lien copié.",hint:"Ce lien ne change pas après les mises à jour.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"Lien permanent pour Downloader / Fire TV. Il récupère toujours la dernière version.",ios:"🍎 iPhone / Safari",iosDesc:"Lien iPhone permanent. Ouvre dans Safari puis Partager → Sur l’écran d’accueil.",smart:"🔗 Lien universel",smartDesc:"Un seul lien détecte automatiquement Android, Fire TV ou iPhone.",iosCopied:"Lien iPhone copié.",fireCopied:"Lien Fire TV copié.",smartCopied:"Lien universel copié."},
ar:{tab:"مشاركة التطبيق",title:"مشاركة DIAMOND",desc:"رابط Android دائم ويفتح دائماً أحدث إصدار.",share:"مشاركة",copy:"نسخ الرابط",open:"فتح",copied:"تم نسخ الرابط.",hint:"هذا الرابط لا يتغير بعد التحديثات.",android:"📱 Android",fire:"📺 Fire TV Stick",fireDesc:"رابط دائم لـ Downloader / Fire TV ويحمّل دائماً أحدث إصدار.",ios:"🍎 iPhone / Safari",iosDesc:"رابط iPhone دائم. افتحه في Safari ثم مشاركة → إضافة إلى الشاشة الرئيسية.",smart:"🔗 رابط موحّد",smartDesc:"رابط واحد يكتشف Android أو Fire TV أو iPhone تلقائياً.",iosCopied:"تم نسخ رابط iPhone.",fireCopied:"تم نسخ رابط Fire TV.",smartCopied:"تم نسخ الرابط الموحّد."}
};
function sal(){const l=localStorage.getItem(SHARE_APP_LANG_KEY)||"sq";return SA[l]?l:"en";}
function sat(k){return SA[sal()]?.[k]??SA.en[k]??k;}
function txt(id,key,p=""){const e=document.getElementById(id);if(e)e.textContent=p+sat(key);}
function val(id,v){const e=document.getElementById(id);if(e)e.value=v;}
function shareAppRender(){
 txt("shareAppTabLabel","tab");txt("shareAppTitle","title");
 txt("shareAndroidTitle","android");txt("shareAppDesc","desc");txt("shareAppHint","hint");txt("shareAppButton","share","🔗 ");txt("copyShareAppButton","copy","📋 ");txt("openShareAndroidButton","open","🌐 ");val("shareAppLink",SHARE_APP_URL);
 txt("shareFireTitle","fire");txt("shareFireDesc","fireDesc");txt("shareFireButton","share","📺 ");txt("copyShareFireButton","copy","📋 ");txt("openShareFireButton","open","🌐 ");val("shareFireLink",SHARE_FIRE_URL);
 txt("shareIosTitle","ios");txt("shareIosDesc","iosDesc");txt("shareIosButton","share","🍎 ");txt("copyShareIosButton","copy","📋 ");txt("openShareIosButton","open","🌐 ");val("shareIosLink",SHARE_IOS_URL);
 txt("shareSmartTitle","smart");txt("shareSmartDesc","smartDesc");txt("shareSmartButton","share","🔗 ");txt("copyShareSmartButton","copy","📋 ");txt("openShareSmartButton","open","🌐 ");val("shareSmartLink",SHARE_SMART_URL);
}
async function markShare(){try{await window.DiamondRegisterShareEvent?.();}catch(_){}}
async function copyUrl(url,inputId,statusId,message,track=true){if(track)await markShare();const s=document.getElementById(statusId);try{await navigator.clipboard.writeText(url);}catch(_){const i=document.getElementById(inputId);i?.select?.();document.execCommand?.("copy");}if(s){s.textContent=message;s.className="message success";}}
async function shareUrl(url,text,inputId,statusId,message){await markShare();try{if(navigator.share){await navigator.share({title:"DIAMOND",text,url});return;}}catch(e){if(e?.name==="AbortError")return;}await copyUrl(url,inputId,statusId,message,false);}
const bind=(prefix,url,descKey,copiedKey)=>{document.getElementById(prefix+"Button")?.addEventListener("click",()=>shareUrl(url,sat(descKey),prefix==="shareApp"?"shareAppLink":prefix+"Link",prefix+"Status",sat(copiedKey)));document.getElementById("copy"+prefix[0].toUpperCase()+prefix.slice(1)+"Button")?.addEventListener("click",()=>copyUrl(url,prefix==="shareApp"?"shareAppLink":prefix+"Link",prefix+"Status",sat(copiedKey),true));};
document.getElementById("shareAppButton")?.addEventListener("click",()=>shareUrl(SHARE_APP_URL,sat("desc"),"shareAppLink","shareAppStatus",sat("copied")));
document.getElementById("copyShareAppButton")?.addEventListener("click",()=>copyUrl(SHARE_APP_URL,"shareAppLink","shareAppStatus",sat("copied"),true));
document.getElementById("openShareAndroidButton")?.addEventListener("click",()=>window.open(SHARE_APP_URL,"_blank","noopener"));
document.getElementById("shareFireButton")?.addEventListener("click",()=>shareUrl(SHARE_FIRE_URL,sat("fireDesc"),"shareFireLink","shareFireStatus",sat("fireCopied")));
document.getElementById("copyShareFireButton")?.addEventListener("click",()=>copyUrl(SHARE_FIRE_URL,"shareFireLink","shareFireStatus",sat("fireCopied"),true));
document.getElementById("openShareFireButton")?.addEventListener("click",()=>window.open(SHARE_FIRE_URL,"_blank","noopener"));
document.getElementById("shareIosButton")?.addEventListener("click",()=>shareUrl(SHARE_IOS_URL,sat("iosDesc"),"shareIosLink","shareIosStatus",sat("iosCopied")));
document.getElementById("copyShareIosButton")?.addEventListener("click",()=>copyUrl(SHARE_IOS_URL,"shareIosLink","shareIosStatus",sat("iosCopied"),true));
document.getElementById("openShareIosButton")?.addEventListener("click",()=>window.open(SHARE_IOS_URL,"_blank","noopener"));
document.getElementById("shareSmartButton")?.addEventListener("click",()=>shareUrl(SHARE_SMART_URL,sat("smartDesc"),"shareSmartLink","shareSmartStatus",sat("smartCopied")));
document.getElementById("copyShareSmartButton")?.addEventListener("click",()=>copyUrl(SHARE_SMART_URL,"shareSmartLink","shareSmartStatus",sat("smartCopied"),true));
document.getElementById("openShareSmartButton")?.addEventListener("click",()=>window.open(SHARE_SMART_URL,"_blank","noopener"));
shareAppRender();
window.DiamondShareApp={activate:shareAppRender,reloadLanguage:shareAppRender,url:SHARE_APP_URL,androidUrl:SHARE_APP_URL,fireUrl:SHARE_FIRE_URL,iosUrl:SHARE_IOS_URL,smartUrl:SHARE_SMART_URL};
