
const T={
sq:{sub:"Jeta islame • kujtesa • shënime",hero:"Gjithçka në një vend, në tri gjuhë.",lang:"Gjuha",back:"Mbrapa",save:"Ruaj",delete:"Fshi",name:"Emri",date:"Data",time:"Ora",title:"Titulli",notes:"Shënime",add:"Shto",alarm:"Aktivizo alarmet",loc:"Përdor vendndodhjen",loading:"Duke ngarkuar…"},
tr:{sub:"İslami yaşam • hatırlatıcı • notlar",hero:"Her şey tek yerde, üç dilde.",lang:"Dil",back:"Geri",save:"Kaydet",delete:"Sil",name:"İsim",date:"Tarih",time:"Saat",title:"Başlık",notes:"Notlar",add:"Ekle",alarm:"Alarmları etkinleştir",loc:"Konumu kullan",loading:"Yükleniyor…"},
de:{sub:"Islamischer Alltag • Erinnerungen • Notizen",hero:"Alles an einem Ort, in drei Sprachen.",lang:"Sprache",back:"Zurück",save:"Speichern",delete:"Löschen",name:"Name",date:"Datum",time:"Uhrzeit",title:"Titel",notes:"Notizen",add:"Hinzufügen",alarm:"Alarme aktivieren",loc:"Standort verwenden",loading:"Lädt…"}
};
const tiles=[
["prayer","🕌","Namazi","Namaz","Gebetszeiten"],["quran","📖","Kurani","Kur’an","Koran"],["wudu","💧","Abdesi","Abdest","Gebetswaschung"],["healing","🤲","Shërime me Kuran","Kur’an ile Şifa","Heilung mit Koran"],["tasbih","📿","Tesbih","Tesbih","Tasbih"],["calendar","🌙","Ditët islame","İslami Günler","Islamische Tage"],["ramadan","✨","Vaktija e Ramazanit","Ramazan Vakitleri","Ramadan-Zeiten"],["forbidden","⚖️","Të ndaluarat","Haramlar","Verbotenes"],["healthy","🍎","Pemë & Perime","Meyve & Sebze","Obst & Gemüse"],["history","🕋","Histori Islame","İslam Tarihi","Islamische Geschichte"],["radio","📻","Radio","Radyo","Radio"],["birthdays","🎂","Ditëlindjet","Doğum Günleri","Geburtstage"],["recipes","🍲","Gatimet","Yemekler","Rezepte"],["appointments","📅","Terminet","Randevular","Termine"]];
let lang=localStorage.getItem("asya_lang")||"sq", current="home";
const app=document.getElementById("app"), back=document.getElementById("backBtn"), langBtn=document.getElementById("langBtn");
function tx(k){return T[lang][k]||k} function idx(){return lang==="sq"?2:lang==="tr"?3:4}
function esc(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function shell(){document.getElementById("subtitle").textContent=tx("sub");langBtn.textContent=lang.toUpperCase();document.getElementById("brand").textContent=current==="home"?"ASYA":titleFor(current);back.classList.toggle("hidden",current==="home")}
function titleFor(k){const x=tiles.find(t=>t[0]===k);return x?x[idx()]:"ASYA"}
function home(){current="home";app.innerHTML=document.getElementById("homeTemplate").innerHTML;document.getElementById("heroText").textContent=tx("hero");const g=document.getElementById("grid");tiles.forEach(t=>{let b=document.createElement("button");b.className="tile";b.innerHTML='<div class="ico">'+t[1]+'</div><h3>'+t[idx()]+'</h3>';b.onclick=()=>open(t[0]);g.appendChild(b)});shell()}
function open(k){current=k;shell(); if(k==="prayer"||k==="ramadan") return prayer(k); if(k==="tasbih") return tasbih(); if(["birthdays","recipes","appointments"].includes(k)) return crud(k); return info(k)}
back.onclick=home;
langBtn.onclick=()=>document.getElementById("langSheet").classList.remove("hidden");document.getElementById("closeLang").onclick=()=>document.getElementById("langSheet").classList.add("hidden");
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem("asya_lang",lang);document.getElementById("langSheet").classList.add("hidden");current==="home"?home():open(current)});
const staticInfo={
wudu:{sq:["Bëj nijetin.","Laji duart 3 herë.","Shpëlaje gojën dhe hundën.","Laje fytyrën 3 herë.","Laji krahët deri te bërrylat.","Jepi mes’h kokës dhe veshëve.","Laji këmbët deri te nyjet."],tr:["Niyet et.","Elleri üç kez yıka.","Ağız ve burnu yıka.","Yüzü üç kez yıka.","Kolları dirseklere kadar yıka.","Başa ve kulaklara mesh et.","Ayakları bileklere kadar yıka."],de:["Absicht fassen.","Hände dreimal waschen.","Mund und Nase spülen.","Gesicht dreimal waschen.","Arme bis zu den Ellbogen waschen.","Über Kopf und Ohren streichen.","Füße bis zu den Knöcheln waschen."]},
forbidden:{sq:["Alkooli dhe dehëset","Mishi i derrit","Bixhozi","Kamata (riba)","Vjedhja dhe mashtrimi","Marrëdhëniet seksuale jashtë martese"],tr:["Alkol ve sarhoş ediciler","Domuz eti","Kumar","Faiz (riba)","Hırsızlık ve dolandırıcılık","Evlilik dışı cinsel ilişki"],de:["Alkohol und Rauschmittel","Schweinefleisch","Glücksspiel","Zins (Riba)","Diebstahl und Betrug","Sexuelle Beziehungen außerhalb der Ehe"]},
healthy:{sq:["Molla – fibra dhe vitamina","Boronicat – antioksidantë","Portokalli – vitaminë C","Spinaqi – folat dhe hekur","Brokoli – fibra dhe vitaminë C","Karota – beta-karoten"],tr:["Elma – lif ve vitaminler","Yaban mersini – antioksidanlar","Portakal – C vitamini","Ispanak – folat ve demir","Brokoli – lif ve C vitamini","Havuç – beta-karoten"],de:["Apfel – Ballaststoffe und Vitamine","Blaubeeren – Antioxidantien","Orange – Vitamin C","Spinat – Folat und Eisen","Brokkoli – Ballaststoffe und Vitamin C","Karotten – Beta-Carotin"]},
history:{sq:["Jeta e Profetit Muhamed ﷺ","Hixhreti nga Meka në Medinë","Beteja e Bedrit","Hapja e Mekës","Katër kalifët e drejtë"],tr:["Hz. Muhammed’in ﷺ hayatı","Mekke’den Medine’ye Hicret","Bedir Savaşı","Mekke’nin Fethi","Dört Raşid Halife"],de:["Das Leben des Propheten Muhammad ﷺ","Hidschra von Mekka nach Medina","Schlacht von Badr","Eroberung Mekkas","Die vier rechtgeleiteten Kalifen"]},
healing:{sq:["El-Fatiha","Ajetul Kursi (2:255)","El-Ihlas, El-Felek, En-Nas","Dua dhe rukje nga Kurani dhe Suneti","Kjo pjesë është për mbështetje shpirtërore dhe nuk zëvendëson mjekun."],tr:["Fatiha","Ayetel Kürsi (2:255)","İhlas, Felak, Nas","Kur’an ve Sünnetten dua ve rukye","Bu bölüm manevi destek içindir; tıbbi tedavinin yerini tutmaz."],de:["Al-Fatiha","Ayat al-Kursi (2:255)","Al-Ikhlas, Al-Falaq, An-Nas","Dua und Ruqya aus Koran und Sunna","Dieser Bereich dient spiritueller Unterstützung und ersetzt keine medizinische Behandlung."]},
calendar:{sq:["Ramazani","Nata e Kadrit","Fitër Bajrami","Dhul-Hixhe","Dita e Arafatit","Kurban Bajrami","Viti i Ri Hixhri","Ashura"],tr:["Ramazan","Kadir Gecesi","Ramazan Bayramı","Zilhicce","Arefe Günü","Kurban Bayramı","Hicri Yılbaşı","Aşure Günü"],de:["Ramadan","Nacht der Bestimmung","Fest des Fastenbrechens","Dhul-Hidscha","Tag von Arafat","Opferfest","Islamisches Neujahr","Aschura"]},
quran:{sq:["Kurani do të shfaqë tekstin arab dhe përkthimin e zgjedhur. Përkthimet e plota do të lidhen në versionin vijues."],tr:["Kur’an Arapça metni ve seçilen çeviriyi gösterecek. Tam çeviriler sonraki sürümde bağlanacak."],de:["Der Koran-Bereich wird den arabischen Text und die gewählte Übersetzung anzeigen. Vollständige Übersetzungen werden in der nächsten Version angebunden."]},
radio:{sq:["Radio shqiptare","Radio turke","Radio islame"],tr:["Arnavut radyoları","Türk radyoları","İslami radyolar"],de:["Albanische Radios","Türkische Radios","Islamische Radios"]}
};
function info(k){const arr=(staticInfo[k]||{})[lang]||[];app.innerHTML='<section class="page"><div class="card"><h2>'+esc(titleFor(k))+'</h2><div class="list">'+arr.map(x=>'<div class="card">'+esc(x)+'</div>').join("")+'</div></div></section>'}
function tasbih(){let n=Number(localStorage.getItem("asya_tasbih")||0);app.innerHTML='<section class="page"><div class="card"><div id="cnt" class="counter">'+n+'</div><button id="plus" class="btn">+1</button><button id="reset" class="btn secondary">Reset</button></div></section>';document.getElementById("plus").onclick=()=>{n++;localStorage.setItem("asya_tasbih",n);document.getElementById("cnt").textContent=n};document.getElementById("reset").onclick=()=>{n=0;localStorage.setItem("asya_tasbih",0);document.getElementById("cnt").textContent=0}}
async function getPrayer(lat,lon){const d=new Date(),date=`${String(d.getDate()).padStart(2,"0")}-${String(d.getMonth()+1).padStart(2,"0")}-${d.getFullYear()}`;const r=await fetch(`https://api.aladhan.com/v1/timings/${date}?latitude=${lat}&longitude=${lon}&method=3`);const j=await r.json();return j.data}
function prayer(mode){app.innerHTML='<section class="page"><div class="card"><h2>'+esc(titleFor(mode))+'</h2><p class="muted">'+tx("loc")+'</p><button id="loadPrayer" class="btn">'+tx("loc")+'</button></div><div id="prayerOut"></div></section>';document.getElementById("loadPrayer").onclick=()=>navigator.geolocation.getCurrentPosition(async p=>{const out=document.getElementById("prayerOut");out.innerHTML='<div class="card">'+tx("loading")+'</div>';try{const d=await getPrayer(p.coords.latitude,p.coords.longitude),t=d.timings;if(mode==="ramadan"){out.innerHTML='<div class="card"><div class="big">Imsak '+esc(t.Imsak)+'</div><div class="big">Iftar '+esc(t.Maghrib)+'</div><p>'+esc(d.date.hijri.date)+' • '+esc(d.date.gregorian.date)+'</p></div>';return}const names=[["Fajr","Sabahu","Sabah","Fajr"],["Dhuhr","Dreka","Öğle","Dhuhr"],["Asr","Ikindia","İkindi","Asr"],["Maghrib","Akshami","Akşam","Maghrib"],["Isha","Jacia","Yatsı","Ischā"]];out.innerHTML='<div class="card">'+names.map(x=>'<div class="prayer-row"><strong>'+x[idx()-1]+'</strong><span>'+esc(t[x[0]])+'</span></div>').join("")+'<button id="alarms" class="btn">'+tx("alarm")+'</button></div>';document.getElementById("alarms").onclick=()=>schedulePrayers(t,names)}catch(e){out.innerHTML='<div class="card">'+esc(String(e))+'</div>'}},e=>alert(e.message),{enableHighAccuracy:true,timeout:15000})}
function schedulePrayers(t,names){try{if(!window.AndroidPrayer){alert("Android alarm bridge unavailable");return}window.AndroidPrayer.requestAlarmPermissions();const now=new Date(), arr=[].concat(...Array.from({length:30},(_,i)=>names.map(n=>{let d=new Date(now);d.setDate(d.getDate()+i);const [h,m]=t[n[0]].split(":").map(Number);d.setHours(h,m,0,0);return {k:n[0],label:n[idx()-1],ms:d.getTime()}})));names.forEach(n=>{const times=arr.filter(x=>x.k===n[0]&&x.ms>Date.now()).map(x=>x.ms);window.AndroidPrayer.schedulePrayer(n[0],n[idx()-1],JSON.stringify(times),lang)});alert("ASYA ✓")}catch(e){alert(String(e))}}
function dataKey(k){return "asya_"+k} function load(k){try{return JSON.parse(localStorage.getItem(dataKey(k))||"[]")}catch(_){return[]}} function save(k,v){localStorage.setItem(dataKey(k),JSON.stringify(v))}
function crud(k){let arr=load(k);const isR=k==="recipes",isA=k==="appointments";app.innerHTML='<section class="page"><div class="card"><h2>'+esc(titleFor(k))+'</h2><input id="f1" placeholder="'+(isR?tx("title"):tx("name"))+'">'+(isR?'<textarea id="f2" placeholder="'+tx("notes")+'"></textarea>':'<input id="f2" type="date"><input id="f3" '+(isA?'type="time"':'type="text"')+' placeholder="'+(isA?tx("time"):tx("notes"))+'">')+'<button id="add" class="btn">'+tx("add")+'</button></div><div id="items"></div></section>';function render(){document.getElementById("items").innerHTML=arr.map((x,i)=>'<div class="card"><strong>'+esc(x.a)+'</strong><p>'+esc(x.b||"")+' '+esc(x.c||"")+'</p><button class="btn danger" data-i="'+i+'">'+tx("delete")+'</button></div>').join("");document.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{arr.splice(Number(b.dataset.i),1);save(k,arr);render()})}document.getElementById("add").onclick=()=>{const a=document.getElementById("f1").value.trim(),b=document.getElementById("f2").value,c=document.getElementById("f3")?.value||"";if(!a)return;arr.push({a,b,c});save(k,arr);render();document.getElementById("f1").value="";document.getElementById("f2").value="";if(document.getElementById("f3"))document.getElementById("f3").value=""};render()}
home();
