plugins {
    id "com.android.application"
}

android {
    namespace "com.pajaziti.familja"
    compileSdk 35

    signingConfigs {
        pajazitiRelease {
            storeFile file("../pajaziti-release.jks")
            storePassword "pajaziti2026"
            keyAlias "pajaziti"
            keyPassword "pajaziti2026"
        }
    }

    defaultConfig {
        applicationId project.findProperty("appId") ?: "com.pajaziti.familja"
        minSdk 23
        targetSdk 35
        versionCode 35
        versionName "5.3"
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.pajazitiRelease
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.pajazitiRelease
        }
    }
}


dependencies {
    implementation "androidx.core:core:1.13.1"
}
